---
title: "agds_report_4"
author: "Naomi Huber"
date: "2023-03-13"
output: html_document
---

```{r}
#Report Exercise 4
library(tidyverse)

#Erarbeitung der ersten Grafik
#Herunterladen der Airquality-Daten
airquality <- datasets::airquality
airquality

#Filtern der Mai-Daten
may_dates <- subset(airquality, Month == 5)
may_dates <- may_dates |>
  group_by(Day) |>
  summarise(temperatures_f = (Temp))
may_dates

#Generieren der Durchschnittstemperatur von Mai
mean_temperature_may <- subset(airquality, Month ==5)
mean_temperature_may <- mean_temperature_may |>
  group_by(Month) |>
  summarise(mean_temperature = mean(Temp))
mean_temperature_may

#Figure 1
plot1 <- ggplot(
  data = may_dates,
  aes(Day, temperatures_f)) +
  geom_line(color = "red4") +
  geom_abline(slope = 0, intercept = 65.54839) +
  labs(title = "Daily Temperature (F°) in May",
       x = "Days in May",
       y = "Temperature (F°)") + 
  theme_grey()

plot1

```

```{r}
#Report Exercise 4
library(tidyverse)
library(ggpubr)

#Erarbeitung der zweiten Grafik
#Herunterladen der Airquality-Daten
airquality <- datasets::airquality

#Generieren einer fortlaufenden Nummerierung
airquality <- airquality |>
  mutate(row_num = row_number())
airquality

#Filtern der relevanten Daten
ozone_days <- subset(airquality, Ozone & row_num)
ozone_days <- ozone_days |>
  group_by(row_num) |>
  summarise(ozone_concentration = Ozone)
ozone_days

temp_days <- subset(airquality, Temp & row_num)
temp_days <- temp_days |>
  group_by(row_num) |>
  summarise(temperature = Temp)
temp_days


#Idee: Korrelation Ozonkonzentration und Temperatur
plot_ozone <- ggplot(
  data = ozone_days,
  aes(row_num, ozone_concentration)) +
  geom_point(color = "blue4") +
  labs(x = "Days (May - Sep)",
       y = "Ozone Concentration")
  theme_classic()
plot_ozone

plot_temperature <- ggplot(
  data = temp_days,
  aes(row_num, temperature)) +
  geom_point(color = "red4") +
  labs(x = "Days (May - Sep)",
       y = "Temperature (F°)")
  theme_classic()
plot_temperature

#Kombinieren zweier Plots
ggarrange(plot_ozone, plot_temperature, nrow = 2, common.legend = TRUE, legend = "bottom")
```

